# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  serialized_pb=_b('\n\x0emessages.proto\"\x8a\x01\n\x0bPalmMessage\x12\x10\n\x08pipeline\x18\x01 \x02(\t\x12\x0e\n\x06\x63lient\x18\x02 \x02(\t\x12\r\n\x05stage\x18\x03 \x02(\x03\x12\x10\n\x08\x66unction\x18\x04 \x02(\t\x12\x0b\n\x03idx\x18\x05 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x06 \x01(\x08\x12\r\n\x05\x63\x61\x63he\x18\x07 \x01(\t\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\"-\n\rBrokerMessage\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x0f\n\x07payload\x18\x02 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PALMMESSAGE = _descriptor.Descriptor(
  name='PalmMessage',
  full_name='PalmMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipeline', full_name='PalmMessage.pipeline', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client', full_name='PalmMessage.client', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stage', full_name='PalmMessage.stage', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='function', full_name='PalmMessage.function', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idx', full_name='PalmMessage.idx', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='PalmMessage.end', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache', full_name='PalmMessage.cache', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='PalmMessage.payload', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=157,
)


_BROKERMESSAGE = _descriptor.Descriptor(
  name='BrokerMessage',
  full_name='BrokerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='BrokerMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='BrokerMessage.payload', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=204,
)

DESCRIPTOR.message_types_by_name['PalmMessage'] = _PALMMESSAGE
DESCRIPTOR.message_types_by_name['BrokerMessage'] = _BROKERMESSAGE

PalmMessage = _reflection.GeneratedProtocolMessageType('PalmMessage', (_message.Message,), dict(
  DESCRIPTOR = _PALMMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:PalmMessage)
  ))
_sym_db.RegisterMessage(PalmMessage)

BrokerMessage = _reflection.GeneratedProtocolMessageType('BrokerMessage', (_message.Message,), dict(
  DESCRIPTOR = _BROKERMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:BrokerMessage)
  ))
_sym_db.RegisterMessage(BrokerMessage)


# @@protoc_insertion_point(module_scope)
